FROM python:3.9
WORKDIR /app

COPY api/requirements.txt api/app.py api/venv api/__pycache__ api/database.py api/job_que.py api/radiology.py api/services.py  api/test.py api/jobs.json ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
EXPOSE 27017
CMD ["gunicorn", "-b", ":5000", "app:app"]